api_platform:
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform/resources']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
#        api_keys:
#            apiKey:
#                name: Authorization
#                type: header
    enable_swagger_ui: true
    enable_re_doc: true
    title: IncaLinks API
    version: 1.0
    show_webby: false
    keep_legacy_inflector: false
    formats:
        jsonld: [ 'application/ld+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
        html: [ 'text/html' ]
