# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    trusted_hosts: null

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
#        handler_id: null
        handler_id: session.handler.native_file
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    # When using the HTTP Cache, ESI allows to render page fragments separately
    # and with different cache configurations for each fragment
    # https://symfony.com/doc/current/http_cache/esi.html
    esi: true
    fragments: true

    php_errors:
        log: true

    ide: null

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
