twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'
#        - 'bootstrap_4_layout.html.twig'

when@test:
    twig:
        strict_variables: true
